// Hardware events - USB HID controller event types

use crate::hardware::display::{
    AmplifierControlPageLayout, StatusPageLayout,
    UnifiedSourceSelectionPageLayout,
};

/// Events generated by the USB HID hardware controller
#[derive(Debug, Clone)]
pub enum HardwareEvent {
    /// Knob turned (positive delta = clockwise, negative = counter-clockwise)
    /// knob_id: 0, 1, or 2 (3 knobs total)
    KnobRotated { knob_id: u8, delta: i8 },

    /// Button pressed down
    /// button_id: 0-5 (6 buttons with screens)
    ButtonPressed { button_id: u8 },

    /// Button released
    /// button_id: 0-5 (6 buttons with screens)
    ButtonReleased { button_id: u8 },

    /// Page navigation button pressed
    /// page_id: 0-2 (3 page buttons)
    PageButtonPressed { page_id: u8 },

    /// Hardware controller plugged in via USB
    DeviceConnected,

    /// Hardware controller unplugged
    DeviceDisconnected,
}

/// Commands to send to the hardware task for display updates
#[derive(Debug, Clone)]
pub enum HardwareCommand {
    /// Update the status page with new layout
    UpdateStatusPage(StatusPageLayout),

    /// T030: Update the amplifier control page with new layout
    UpdateAmplifierPage(AmplifierControlPageLayout),

    /// Update the unified source selection page with new layout
    UpdateUnifiedSourceSelectionPage(UnifiedSourceSelectionPageLayout),

    /// Display an error message on all screens
    /// T073: Display error when command fails
    ShowError(String),
}
